### ISSUE TITLE
Add option sensitive_cols

### ISSUE THREAD

**Issue by MichaelDismorrMD** [drwernicke/dumbr#1]
Great package!
Consider adding an option in the function for sensitive columns that not will be included in the dummy dataset, e.g. columns containing names, adressen etc.
Should work by adding a line like 
```r
 %>% select(!(sensitive_cols)) %>%
```

This can also serve to remind the user that this data needs to be considered.

**Comment by reitancorp** [comment]
Option has been added. Note that you just as well could use %>% select().
